### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by AlessioSam** [InhwanBae/LMTrajectory#1]
Hi,
thank you for the work you have done, very nice!
When will the code for the release be ready?

Thank you,
Alessio

**Comment by InhwanBae** [comment]
Hi @AlessioSam,

Sorry for the late reply. I've been busy with ongoing submissions and rebuttals. I have just organized and released the LMTraj-ZERO source code, and LMTraj-SUP will be released within this week.

**Comment by InhwanBae** [comment]
Hi @AlessioSam,

All the source code has been released. Check it out!

**Comment by InhwanBae** [comment]
I'm closing this issue for now. Feel free to open another issue if you have any further questions!
