### ISSUE TITLE
About ETH/UCY zero-shot results

### ISSUE THREAD

**Issue by RiHY99** [InhwanBae/LMTrajectory#8]
Thanks for your work.
I want to know if the zero-shot results on ETH/UCY are all calculated by multimodal predictions? If predictions are all multimodal, is the K equal to 20? And how to produce multimodal predictions for these methods: Linear, Kalman Filter, AutoTrajectory, and LMTraj-ZERO-GPT3.5/GPT4?

**Comment by InhwanBae** [comment]
Hi @RiHY99,

You are correct. We measure the zero-shot benchmark with k=20 settings, as ChatGPT produces different outputs across multiple runs. For algorithmic models, we assume they generate the same outputs in multiple runs and use a single output for evaluation. I hope this helps!

**Comment by InhwanBae** [comment]
I'm closing this issue for now. Feel free to open another issue if you have any further questions!
